#!/bin/sh

set -e
. vars

# Generate the git repo for the 2.11BSD project.

# Blow away old git repo
[ -d $GITREPO ] && clean_tree $GITREPO
mkdir -p $GITREPO

# Initialize the repo
chdir $GITREPO
git init
echo Patch-Level: -1 > PATCH-LEVEL
git checkout -b 211bsd
git add PATCH-LEVEL
git commit -m"2.11BSD history reconstruction project, initial empty commit"

# Copy the initial tree
# This list is ugly, but not all the src is under /usr/src
(cd $ROOT211; tar cf - GENALLSYS README VERSION dev etc \
	usr/adm usr/lib usr/dict usr/doc usr/guest usr/hosts usr/include \
	usr/pub usr/skel usr/spool usr/src) | tar xvf -

# Note: XXX
echo Patch-Level: 0 > PATCH-LEVEL
git add *
git commit -m"Import 2.11BSD, as released, as reconstructed"
